
spring.datasource.url=jdbc:mysql://localhost:3306/facturacion_db?serverTimezone=UTC

spring.datasource.username=root
spring.datasource.password=2000


spring.jpa.hibernate.ddl-auto=update


spring.jpa.show-sql=true

# --- Configuración Twilio (WhatsApp) ---
twilio.account.sid=PON_TU_SID_AQUI
twilio.auth.token=PON_TU_TOKEN_AQUI
twilio.phone.number=+14155238886